# Generated by Django 6.0.1 on 2026-02-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_comment_is_published_comment_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='apartments_count',
            field=models.IntegerField(default=0, help_text='Общее количество квартир в доме', verbose_name='Количество квартир'),
        ),
        migrations.AddField(
            model_name='house',
            name='cadastral_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кадастровый номер'),
        ),
        migrations.AddField(
            model_name='house',
            name='land_area',
            field=models.FloatField(blank=True, help_text='в м²', null=True, verbose_name='Площадь участка'),
        ),
        migrations.AddField(
            model_name='house',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Например: 53.7683', null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='house',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Например: 87.1597', null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='house',
            name='playground',
            field=models.BooleanField(default=False, verbose_name='Детская площадка'),
        ),
        migrations.AddField(
            model_name='house',
            name='sport_ground',
            field=models.BooleanField(default=False, verbose_name='Спортивная площадка'),
        ),
        migrations.AddField(
            model_name='house',
            name='total_area',
            field=models.FloatField(blank=True, help_text='в м²', null=True, verbose_name='Общая площадь дома'),
        ),
    ]
