# Generated by Django 6.0.1 on 2026-02-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_house_apartments_count_house_cadastral_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='cadastral_number',
        ),
        migrations.RemoveField(
            model_name='house',
            name='has_elevator',
        ),
        migrations.RemoveField(
            model_name='house',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='house',
            name='management_company',
        ),
        migrations.RemoveField(
            model_name='house',
            name='playground',
        ),
        migrations.RemoveField(
            model_name='house',
            name='sport_ground',
        ),
        migrations.RemoveField(
            model_name='house',
            name='total_area',
        ),
        migrations.AddField(
            model_name='house',
            name='ceiling_height',
            field=models.FloatField(blank=True, help_text='в метрах', null=True, verbose_name='Высота потолков'),
        ),
        migrations.AddField(
            model_name='house',
            name='ceiling_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип перекрытий'),
        ),
        migrations.AddField(
            model_name='house',
            name='elevator_count',
            field=models.IntegerField(default=0, help_text='Количество лифтов', verbose_name='Лифтов'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_garbage_chute',
            field=models.BooleanField(default=False, verbose_name='Мусоропровод'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_gas',
            field=models.BooleanField(default=False, verbose_name='Газ'),
        ),
        migrations.AddField(
            model_name='house',
            name='heating_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отопление'),
        ),
        migrations.AddField(
            model_name='house',
            name='house_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип дома'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_demolition',
            field=models.BooleanField(default=False, verbose_name='Под снос'),
        ),
        migrations.AddField(
            model_name='house',
            name='is_emergency',
            field=models.BooleanField(default=False, verbose_name='Аварийность'),
        ),
        migrations.AlterField(
            model_name='house',
            name='apartments_count',
            field=models.IntegerField(default=0, verbose_name='Квартир'),
        ),
        migrations.AlterField(
            model_name='house',
            name='entrance_count',
            field=models.IntegerField(default=1, verbose_name='Парадных (подъездов)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor_count',
            field=models.IntegerField(default=1, verbose_name='Этажность'),
        ),
    ]
