# Generated by Django 6.0.1 on 2026-02-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_house_cadastral_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год отчета')),
                ('report_file', models.FileField(help_text='Загрузите PDF файл с отчетом', upload_to='reports/%Y/', verbose_name='PDF файл')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название отчета')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Отчет по дому',
                'verbose_name_plural': 'Отчеты по домам',
                'ordering': ['-year', 'house'],
                'unique_together': {('house', 'year')},
            },
        ),
    ]
