# Generated by Django 6.0.1 on 2026-02-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_housereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Текущая задолженность по квартплате', max_digits=10, verbose_name='Задолженность'),
        ),
    ]
