# Generated by Django 6.0.1 on 2026-02-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_apartment_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='houses',
            field=models.ManyToManyField(blank=True, help_text='Выберите дома, для которых предназначена новость (если не выбрано - для всех)', related_name='news', to='core.house', verbose_name='Дома'),
        ),
    ]
