# Generated by Django 6.0.1 on 2026-02-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_news_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='houses',
            field=models.ManyToManyField(blank=True, help_text='Выберите дома, для которых предназначена новость', related_name='news', to='core.house', verbose_name='Дома'),
        ),
    ]
