# Generated by Django 6.0.1 on 2026-04-29 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_news_houses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бригады')),
                ('chief', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brigade', to=settings.AUTH_USER_MODEL, verbose_name='Бригадир')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('status', models.CharField(choices=[('new', '🟡 Новая'), ('in_progress', '🔵 В работе'), ('completed', '✅ Завершена')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало работ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершена')),
                ('materials_used', models.TextField(blank=True, verbose_name='Использованные материалы')),
                ('hours_worked', models.FloatField(blank=True, null=True, verbose_name='Часов затрачено')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('assigned_brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.brigade', verbose_name='Бригада')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workorders', to=settings.AUTH_USER_MODEL, verbose_name='Заявитель')),
            ],
            options={
                'verbose_name': 'Рабочая заявка',
                'verbose_name_plural': 'Рабочие заявки',
            },
        ),
    ]
