# Generated by Django 6.0.1 on 2026-04-29 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_brigade_workorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brigade',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='brigade_member', to=settings.AUTH_USER_MODEL, verbose_name='Члены бригады'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='chief',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brigade_chief', to=settings.AUTH_USER_MODEL, verbose_name='Бригадир'),
        ),
    ]
