# Generated by Django 6.0.1 on 2026-04-29 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_brigade_members_alter_brigade_chief'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='assigned_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.brigade', verbose_name='Бригада'),
        ),
        migrations.AddField(
            model_name='request',
            name='hours_worked',
            field=models.FloatField(blank=True, null=True, verbose_name='Часов затрачено'),
        ),
        migrations.AddField(
            model_name='request',
            name='resources_used',
            field=models.TextField(blank=True, verbose_name='Потраченные ресурсы'),
        ),
        migrations.AddField(
            model_name='request',
            name='work_notes',
            field=models.TextField(blank=True, verbose_name='Примечания бригады'),
        ),
        migrations.AddField(
            model_name='request',
            name='work_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало работ'),
        ),
        migrations.DeleteModel(
            name='WorkOrder',
        ),
    ]
