# Generated by Django 6.0.1 on 2026-02-05 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Будет использоваться для входа в систему', max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(help_text='Введите ФИО полностью как в паспорте', max_length=150, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Email подтвержден')),
                ('verification_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Код подтверждения')),
                ('apartment_confirmed', models.BooleanField(default=False, verbose_name='Квартира подтверждена')),
                ('personal_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Лицевой счет')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждённый жилец')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created_at'],
            },
        ),
    ]
