# Generated by Django 6.0.1 on 2026-02-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Загрузите фото профиля', null=True, upload_to='avatars/%Y/%m/', verbose_name='Аватар'),
        ),
    ]
