# Generated by Django 6.0.1 on 2026-04-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_brigade_chief',
            field=models.BooleanField(default=False, verbose_name='Бригадир'),
        ),
    ]
